import React from 'react'
import styles from './about.module.css'
export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
}
function page() {
  return (
    <div>

    <h1 className={styles.header}> Hello about page</h1>
      
    </div>
  )
}

export default page
