'use client'
import './globals.css'
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import Footer from './components/Footer'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

useEffect(()=>{

 require('../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js');


})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar/>
      {children} 
      <Footer/>  
      </body>
    </html>
  )
}
